<?php

/*

+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube help plugin                            |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Milan Kozak <hodza@hodza.net>                                 |
+-----------------------------------------------------------------------+

@version $Id: cs_CZ.inc,v 1.1 2011/08/01 19:22:05 eldy Exp $

*/

$labels = array();
$labels['help'] = 'Nápověda';
$labels['about'] = 'O aplikaci';
$labels['license'] = 'Licence';

?>
