<?php
//
// File generated by Dolibarr installer 3.3.1 on 2013-04-23 11:32:10
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://localhostdolibarr/dolipos';
$dolibarr_main_document_root='/home/ldestailleur/git/nltechno/dolicloudimages/dolipos/src/htdocs';
//$dolibarr_main_url_root_alt='http://localhostdolibarr/dolicloud/htdocs/custom';
//$dolibarr_main_document_root_alt='/home/ldestailleur/git/nltechno/dolicloudimages/dolibarr/src/htdocs/custom';
$dolibarr_main_data_root='/tmp';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='dolipos';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='dolipos';
$dolibarr_main_db_pass='dolipos-do';
$dolibarr_main_db_type='mysql';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
$dolibarr_main_authentication='dolibarr';

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='8ff7101031a1adfbdada138a8a640f37';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>