<?php

/*

+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube userinfo plugin                        |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Milan Kozak <hodza@hodza.net>                                 |
+-----------------------------------------------------------------------+

@version $Id: cs_CZ.inc,v 1.1 2011/08/01 19:22:07 eldy Exp $

*/

$labels = array();
$labels['infosfor'] = 'Informace pro';
$labels['userinfo'] = 'Uživatel';
$labels['created'] = 'Vytvořen';
$labels['lastlogin'] = 'Naspoledy přihlášen';
$labels['defaultidentity'] = 'Výchozí identita';

?>