= GUIDE UTILISATEUR =
:subtitle: Guide des utilisateurs - v8




== Introduction ==

La douzième édition de ce livre paraît, alors que la réputation de *Dolibarr* est déjà bien établie. Seize ans après les premières lignes de code réalisées par Rodolphe Quiédeville présent sur le stand de *Dolibarr* au salon Solutions Linux ( https://www.facebook.com/photo.php?fbid=704623766274752&set=pb.132555040148297.-2207520000.1403686530.&type=1&theater[voir] ), sous la conduite de Laurent Destailleur et avec l'aide de nombreux contributeurs ( https://github.com/Dolibarr/dolibarr/graphs/contributors[voir] ), l’ERP/CRM *Dolibarr* est devenu un incontournable dans le monde du logiciel Open Source.  +
*Dolibarr* a fait cette année son DevCamp de printemps à Nancy les 9,10 et 11 mars 2018. L'un des sujets traités fut l'utilisation du nouveau module ModuleBuilder pour créer vos propres modules. Vous pouvez utiliser le nouvel exemple de code trouvé dans les fichiers du répertoire modulebuilder pour inclure le fichier main.inc.php dans votre fichier de module externe => La seule façon de charger l'environnement de framework dolibarr est la façon dont votre Dolibarr et votre module sont installés (dans custom, en root, en utilisant des liens symboliques, à l'intérieur d'un hôte virtuel ou en utilisant un alias, quelle que soit la configuration de votre serveur web, ...). Une autre présentation fut faite sur le module de création de site web...le futur se présente bien ! +
La version *8.0* de *Dolibarr* est un pas supplémentaire vers la maturité déjà reconnue de la solution ERP & CRM de gestion d'activité professionnelle ou associative la plus accessible aux petites et moyennes entreprises. Vous aurez remarqué que l’on est passé directement de la version *7.0* à la version *8.0* sans décliner toutes les décimales de la *7.0*.
En effet à partir de la version *4.0* chaque nouvelle version saute d’unité en unité, si vous m’avez bien suivi...la nouvelle version est donc la version *8.0* ( J’en vois qui ne suivent pas au fond de la classe :). Les versions *8.0.1*, *8.0.2* etc… correspondront à des versions de corrections de bogues.
Tous les modules fonctionnels ont été améliorés, avec en particulier l’ajout d’un module pour les déclinaisons de produits, ainsi que le module de logs inaltérables nécessaire pour l’attestation. L'association a créé une page dédiée pour fournir des renseignements sur la loi de finances, les modalités pour faire attester votre environnement et les travaux en cours, à voir https://wiki.dolibarr.org/index.php/Loi_article_88_finances_2016_et_Certification_NF525_ou_LNE[ici]. La génération de prélèvements SEPA est maintenant mature. Ajout des modules Ticket(fourni dans le core de Dolibarr par Jean François Ferry), WebDAV ainsi que du module Comptabilité Expert(Comptabilité double partie), grâce à https://philippe.scoffoni.net/campagne-financement-participative-dolibarr/[une campagne de financement participative]. Refonte du module Intervention avec alignement du code sur celui des autres modules : Gestion des triggers, événements automatiques, hooks, documents PDF visible dans la GED, création d’une propale depuis le module. Amélioration du module Notification qui offre maintenant la possibilité de faire des notifications fixes et de nombreuses autres fonctionnalités ajoutées.  +
Avec _transifex,_ le nouveau processus de traduction, aider à la traduction de *Dolibarr* n'a jamais été aussi simple. Aucune connaissance technique n'est requise, créez simplement un compte sur https://www.transifex.com/[transifex.com] et traduisez depuis l'interface. +
L'association *Dolibarr* a de plus lié le système au service de traduction de Google, ce qui permet si besoin d'avoir des propositions automatiquement suggérées. Ceci réduit encore le temps de travail. +
Les traductions soumises sur _transifex_ seront fréquemment synchronisées avec les sources officielles du projet *Dolibarr*. +
Notez que pour le moment, ce nouveau système doit être utilisé pour tous les langages, sauf _en_US_ (la langue source), _fr_FR_, _es_ES_ et _es_CA_ (dont les contributeurs continuent d'utiliser majoritairement GitHub). De même pour les "langues alternatives" (par example _es_MX_, _es_PR_, _es_PY_) car ces dernières sont des variantes d'une autre langue (par exemple _es_ES_) qui ne nécessitent de ne maintenir que le delta des lignes qui diffèrent. Pour tout autre langage, merci de nous aider à traduire *Dolibarr* en vous inscrivant comme traducteur en ligne de *Dolibarr* sur la page https://www.transifex.com/projects/p/dolibarr/[https://www.transifex.com/projects/p/dolibarr/]. En quelques minutes, vous pourrez compléter/corriger votre langue. De même, vous pouvez juste « approuver » les traductions qui sont déjà traduites mais non encore approuvées. +
Les fonctionnalités et règles de développement ont également été enrichies afin d'améliorer la qualité et l'efficacité de la plate-forme de plugins complémentaires http://www.dolistore.com/[DoliStore], ainsi la plupart des modules de cette plate-forme ont aussi été mis à jour en parallèle et sont disponibles en même temps que la sortie de *Dolibarr*. +
Notez que depuis la version *3.4.0* *Dolibarr* est diffusé sous licence *GPLv3+*.

*Objectifs et contenu de ce livre* +
L'auteur Philippe GRAND (_aka _http://www.dolibarr.fr/forum/profil/635-grandoc[_grandoc]_) y participant lui même s'est largement inspiré du http://wiki.dolibarr.org/index.php/Main_Page[wiki de Dolibarr]. *Le contenu de ce livre est soumis à une licence creative Commons ( CC-BY-SA )*. +
*Dolibarr* étant par essence modulaire, ce document décrit module par module les étapes à suivre pour réaliser les processus minimaux à travers *Dolibarr*. +
Ce guide d’instructions prétend donner à l’utilisateur une vision globale, rapide, et non spécifique, de chacun des différents processus et fonctionnalités, afin que celui ci puisse en cas d’oubli, facilement s’éclairer de manière simple et pratique. Nous rappelons qu’il ne s’agit pas d’un manuel complet, seulement d’un guide rapide. +
*Avertissement* : Les explications et démonstration du livre sont actuellement faites sur une version *8.0* de *Dolibarr*. Cce guide est en constante actualisation, de ce fait nous vous recommandons de porter toute votre attention aux nouvelles versions qui suivront l’évolution de *Dolibarr* et qui seront mises à la disposition de ses utilisateurs sur le http://www.dolistore.com/[DoliStore].






