<?php

/*

+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube markasjunk plugin                      |
| Copyright (C) 2005-2009, RoundCube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Milan Kozak <hodza@hodza.net>                                 |
+-----------------------------------------------------------------------+

@version $Id: cs_CZ.inc,v 1.1 2010/08/17 23:08:42 eldy Exp $

*/

$labels = array();
$labels['buttontitle'] = 'Označit jako Spam';
$labels['reportedasjunk'] = 'Úspěšně nahlášeno jako Spam';

?>